import Head from "next/head"
import Layout from "@/components/Layout"
import Image from "next/image"
import profilePic from "../../public/images/profile/developer-pic-1.png"
import AnimatedText from "@/components/AnimatedText"
import Link from "next/link"
import {LinkArrow} from "@/components/Icons"
import HireMe from "@/components/HireMe"
import lightBulb from "../../public/images/svgs/miscellaneous_icons_1.svg"
export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
            </Head>
            <main className="flex items-center text-dark w-full min-h-screen md:min-h-min dark:text-light">
                <Layout className="pt-0 md:pt-16 sm:py-8">
                    <div className="flex items-center justify-between w-full lg:flex-col">
                        <div className="w-1/2 md:w-full">
                            <Image
                                priority={true}
                                sizes="(max-width: 768px) 100vw,
                                (max-width: 1200px) 50vw,
                                50vw"
                                src={profilePic}
                                alt="Sammy Shehter"
                                className="w-full h-auto lg:hidden md:inline-block md:w-full md:pb-4"
                            />
                        </div>
                        <div className="w-1/2 flex flex-col items-center self-center lg:w-full lg:text-center">
                            <AnimatedText
                                text="Turning Vision Into Reality With Code And
                                Design."
                                className="text-left  text-6xl xl:text-5xl lg:text-center lg:text-6xl md:text-5xl sm:text-3xl"
                            />
                            <p className="my-4 text-base font-medium md:text-sm sm:text-xs">
                                As a skilled full-stack developer, I am
                                dedicated to turning ideas into innovative web
                                applications. Explore my latest projects and
                                articles, showcasing my expertise in React.js
                                and web development.
                            </p>
                            <div className="flex items-center self-start mt-2 lg:self-center">
                                <Link
                                    href="/dummy.pdf"
                                    target="_blank"
                                    download={true}
                                    className="flex items-center bg-dark text-light p-2.5 px-6 rounded-lg text-lg font-semibold border-2 border-solid border-transparent hover:border-dark hover:bg-light hover:text-dark dark:bg-light dark:text-dark hover:dark:bg-dark hover:dark:text-light hover:dark:border-light lg:p-2 md:px-4 md:text-base"
                                >
                                    Resume <LinkArrow className="w-6 ml-1" />
                                </Link>
                                <Link
                                    href="mailto:sammyshehter@gmail.com"
                                    className="ml-5 text-lg font-medium capitalize text-dark underline dark:text-light md:text-base"
                                >
                                    Contact
                                </Link>
                            </div>
                        </div>
                    </div>
                </Layout>
                <HireMe />
            </main>
        </>
    )
}
